excoincial-peatio/config/routes.rb
# encoding: UTF-8
# frozen_string_literal: true

# Explicitly require "lib/peatio.rb".
# You may be surprised why this line also sits in config/application.rb.
# The same line sits in config/application.rb to allows early access to lib/peatio.rb.
# We duplicate line in config/routes.rb since routes.rb is reloaded when code is changed.
# The implementation of ActiveSupport's require_dependency makes sense to use it only in reloadable files.
# That's why it is here.
require_dependency 'peatio'

Dir['app/models/deposits/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }
Dir['app/models/withdraws/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do

  get 'symbol_detail/show/:currency' => 'symbol_detail#show'

  root 'welcome#index'

  get '/fidelitypay/deposit' => 'pay_gate_return#index'

  get '/aboutus' => 'welcome#aboutus'
  get '/login_privacy' => 'welcome#login_privacy'
  get '/login_alert' => 'welcome#login_alert'
  get '/cookies_eu' => 'welcome#cookies_eu'
  get '/invaild_browser' => 'welcome#invaild_browser'

  post 'welcome/update_profile_image'
  post 'welcome/update_profile',:path => 'update_profile'
  post 'welcome/change_pwd',:path => 'change_pwd'
  get 'welcome/approve_login',:path => 'member/:id/approve_login'
  get 'welcome/confirm_withdrawal',:path => 'member/:id/confirm_withdrawal'
  get 'welcome/disable_account',:path => 'member/:id/disable_account'

  get 'welcome/coins_info',:path => 'coins-info'
  get '/login_supportfooter' => 'welcome#login_supportfooter'
  get '/support' => 'welcome#login_supportfooter'
  get '/login_terms_cond' => 'welcome#login_terms_cond'
  get '/terms' => 'welcome#login_terms_cond'
  get '/conditions' => 'welcome#login_terms_cond'
  get '/termsandconditions' => 'welcome#login_terms_cond'
  get '/privacy' => 'welcome#login_privacy'
  get '/setmode/:mode' => 'welcome#setmode'

  get '/login' => 'sessions#callback', :as => :login
  get '/login/confirm', to: redirect('/accounts/login/confirm')
  post '/login/confirm', to: redirect('/accounts/login/confirm')
#, to: redirect{ |params, request| ["/accounts/login#{params[:login_referer_path]}", request.query_string.presence].compact.join('?') }
  get '/register', to: redirect('/accounts/register')
  get '/register/confirm', to: redirect('/accounts/register/confirm')
  get '/unlock', to: redirect('/accounts/unlock')
  get '/forgot', to: redirect('/accounts/forgot')

  get '/logout' => 'sessions#destroy', :as => :logout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: %i[get post]

  scope module: :private do
    resources :rewards, only: :index

    resources :settings, only: [:index]

    resources :withdraw_destinations, only: %i[ create update ]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
        get :funds_json
      end
    end

    resources :bank_details

    resources 'deposits/:currency', controller: 'deposits', as: 'deposit', only: %i[ destroy ] do
      collection {
        post 'gen_address'
        get '/',  action: :show
        post 'create_payment', action: :create_payment
      }
    end


    resources 'withdraws/:currency', controller: 'withdraws', as: 'withdraw', only: %i[ create destroy ] do
      collection {
        get '/', action: :show
      }
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history
    get '/history/open_orders' => 'history#open_orders', as: :open_order_history

    resources :markets, only: [:show], constraints: MarketConstraint do
      resources :orders, only: %i[ index destroy ] do
        collection do
          post :clear
        end
      end
      resources :order_bids, only: [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, only: [:create] do
        collection do
          post :clear
        end
      end
    end
  end

  get 'health/alive', to: 'public/health#alive'
  get 'health/ready', to: 'public/health#ready'

  get 'trading/:market_id', to: BlackHoleRouter.new, as: :trading
#  get '/exchange/:market_id', to: BlackHoleRouter.new, as: :trading

  get '/trading', to: redirect('/trading/ethbtc')
  get '/exchange', to: redirect('/trading/ethbtc')

  draw :admin

  get '/swagger', to: 'swagger#index'

  mount APIv2::Mount => APIv2::Mount::PREFIX
  mount ManagementAPIv1::Mount => ManagementAPIv1::Mount::PREFIX
end

excoincial-peatio/app/controllers/admin/withdraws/base_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

require_dependency 'admin/base_controller'

module Admin
  module Withdraws
    class BaseController < BaseController

    protected

      def currency
        Currency.where(type: self.class.name.demodulize.underscore.gsub(/_controller\z/, '').singularize)
                .find(params[:currency])
      end

      def find_withdraw
        model     = "::Withdraws::#{self.class.name.demodulize.gsub(/Controller\z/, '').singularize}".constantize
        @withdraw = model.where(currency: currency).find(params[:id])
      end
    end
  end
end

excoincial-peatio/app/controllers/admin/withdraws/coins_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

require_dependency 'admin/withdraws/base_controller'

module Admin
  module Withdraws
    class CoinsController < BaseController
      before_action :find_withdraw, only: [:show, :update, :destroy]

      def index
        case params.fetch(:state, 'all')
        when 'all'
          all_withdraws
        when 'latest'
          latest_withdraws
        when 'pending'
          pending_withdraws
        end
      end

      def show

      end

      def update
        case params.fetch(:event)
        when 'process'
          process!
        when 'load'
          load!
        when 'reprocess'
          reprocess!
        end
      end

      def destroy
        @withdraw.reject!
        redirect_to :back, notice: t('admin.withdraws.coins.update.notice')
      end

      private

      def all_withdraws
        @all_withdraws     = ::Withdraws::Coin.where(currency: currency)
                                              .order(id: :desc)
                                              .includes(:member, :currency, :blockchain)
      end

      def latest_withdraws
        @latest_withdraws  = ::Withdraws::Coin.where(currency: currency)
                                              .where('created_at > ?', 1.day.ago)
                                              .order(id: :desc)
                                              .includes(:member, :currency, :blockchain)
      end

      def pending_withdraws
        @pending_withdraws = ::Withdraws::Coin.where(currency: currency, aasm_state: 'accepted')
                                              .where('created_at  < ?', 1.minute.ago)
                                              .order(id: :desc)
                                              .includes(:member, :currency, :blockchain)
      end

      def process!
        @withdraw.transaction do
          @withdraw.accept!
          @withdraw.process!
        end
        redirect_to :back, notice: t('admin.withdraws.coins.update.notice')
      end

      def reprocess!
        @withdraw.reprocess!
        redirect_to :back, notice: t('admin.withdraws.coins.update.notice')
      end

      def load!
        @withdraw.transaction do
          @withdraw.update!(txid: params.fetch(:txid))
          @withdraw.load!
        end
        redirect_to :back, notice: t('admin.withdraws.coins.update.notice')
      end
    end
  end
end

excoincial-peatio/app/controllers/admin/withdraws/fiats_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

require_dependency 'admin/withdraws/base_controller'

module Admin
  module Withdraws
    class FiatsController < BaseController
      before_action :find_withdraw, only: [:show, :update, :destroy]

      def index
        case params.fetch(:state, 'all')
        when 'all'
          all_withdraws
        when 'latest'
          latest_withdraws
        when 'pending'
          pending_withdraws
        end
      end

      def index
        @latest_withdraws  = ::Withdraws::Fiat.where(currency: currency)
                                              .where('created_at <= ?', 1.day.ago)
                                              .order(id: :desc)
                                              .includes(:member, :currency)
        @all_withdraws     = ::Withdraws::Fiat.where(currency: currency)
                                              .where('created_at > ?', 1.day.ago)
                                              .order(id: :desc)
                                              .includes(:member, :currency)
      end

      def show

      end

      def update
        @withdraw.transaction do
          @withdraw.accept!
          @withdraw.process!
          @withdraw.dispatch!
          @withdraw.success!
        end
        redirect_to :back, notice: t('admin.withdraws.fiats.update.notice')
      end

      def destroy
        @withdraw.reject!
        redirect_to :back, notice: t('admin.withdraws.fiats.update.notice')
      end

      private

        def all_withdraws
          if (currency.escrow?)
            @all_withdraws = 
              ::Withdraws::Escrow.where(currency: currency)
                                 .order(id: :desc)
                                 .includes(:member, :currency)
          elsif (currency.fiat?)
            @all_withdraws = 
              ::Withdraws::Fiat.where(currency: currency)
                               .order(id: :desc)
                               .includes(:member, :currency)
          end
        end

        def latest_withdraws
          if (currency.escrow?)
            @latest_withdraws = 
              ::Withdraws::Escrow.where(currency: currency)
                                 .where('created_at > ?', 1.day.ago)
                                 .order(id: :desc)
                                 .includes(:member, :currency)
          elsif (currency.fiat?)
            @latest_withdraws = 
              ::Withdraws::Fiat.where(currency: currency)
                               .where('created_at > ?', 1.day.ago)
                               .order(id: :desc)
                               .includes(:member, :currency)
          end
        end

        def pending_withdraws
          if (currency.escrow?)
            @pending_withdraws = 
              ::Withdraws::Escrow.where(currency: currency, aasm_state: 'accepted')
                                 .where('created_at  < ?', 1.minute.ago)
                                 .order(id: :desc)
                                 .includes(:member, :currency)
          elsif (currency.fiat?)
            @pending_withdraws = 
              ::Withdraws::Escrow.where(currency: currency, aasm_state: 'accepted')
                                 .where('created_at  < ?', 1.minute.ago)
                                 .order(id: :desc)
                                 .includes(:member, :currency)
          end
        end


#     def process!
#       @withdraw.transaction do
#         @withdraw.accept!
#         @withdraw.process!
#       end
#       redirect_to :back, notice: 'Withdraw successfully processed!'
#     end
#

    end
  end
end

excoincial-peatio/app/controllers/private/bank_details_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class BankDetailsController < BaseController
    layout 'funds'
#    before_action :auth_member!

  def index
      @bank_details = current_user.bank_details.order(id: :desc)
    end

  def new
      @bank_detail = BankDetail.new
    end

  def create
      @bank_detail = current_user.bank_details.new(bank_params)
      if @bank_detail.save
        flash[:notice] = "Bank details successfully created"
        redirect_to bank_details_path
      else
        flash[:notice] = @bank_detail.errors.full_messages
        render :new
      end
    end

  def edit
      @bank_detail = BankDetail.find(params[:id])
    end

  def update
      @bank_detail = BankDetail.find(params[:id])
      if @bank_detail.update(bank_params)
        flash[:notice] = "Bank details successfully updated"
        redirect_to bank_details_path
      else
        flash[:notice] = @bank_detail.errors.full_messages
        render :edit
      end
    end

  def destroy
      @bank_detail = BankDetail.find(params[:id])
      @bank_detail.destroy
      redirect_to bank_details_path
    end

  private

  def bank_params
      params.require(:bank_detail).permit!
    end
  end
end

excoincial-peatio/app/controllers/private/base_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class BaseController < ::ApplicationController
    before_filter :no_cache, :auth_member!

    private

    def deposits_must_be_permitted!
      if current_user.level < ENV.fetch('MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT').to_i
        redirect_to settings_path, alert: t('private.settings.index.deposits_must_be_permitted')
      end
    end

    def withdraws_must_be_permitted!
      if current_user.level < ENV.fetch('MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW').to_i
        redirect_to settings_path, alert: t('private.settings.index.withdraws_must_be_permitted')
      end
    end

    def trading_must_be_permitted!
      if current_user.level < ENV.fetch('MINIMUM_MEMBER_LEVEL_FOR_TRADING').to_i
        redirect_to settings_path, alert: t('private.settings.index.trading_must_be_permitted')
      end
    end

    def no_cache
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Sat, 03 Jan 2009 00:00:00 GMT"
    end
  end
end

excoincial-peatio/app/controllers/private/deposits_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class DepositsController < BaseController
    before_action :deposits_must_be_permitted!
    protect_from_forgery :except => [:create_payeer]

    layout 'funds'

    def gen_address
      current_user.ac(currency).payment_address
      head 204
    end

    def destroy
      record = current_user.deposits.find(params[:id]).lock!
      if record.cancel!
        head 204
      else
        head 422
      end
    end

    def show
      if currency.fiat?
        @txid = "PG#{(0...8).map { ('a'..'z').to_a[rand(26)] }.join}#{Time.now.to_i}"          
        return render "fiat_show", layout: "fiat_funds"
      end
      begin
        @deposit_address = current_user.ac(currency).payment_address
      rescue => e
        Rails.logger.error { "current_user: " + current_user.inspect }
        Rails.logger.error { "currency: " + currency.inspect }
        Rails.logger.error { current_user.ac(currency).inspect }
        report_exception e
        raise e
      end
    end

    def create_payment
      d = Deposit.new(member_id: current_user.id, amount: params[:amount].to_f, currency: currency, type: "Deposits::Fiat", txid: params[:txid], address: params[:address])
      d.save
      respond_to do |format|
        format.json { head :ok }
      end
    end

    private

    def currency
      @currency ||= Currency.enabled.find(params[:currency])
    end

  end
end

excoincial-peatio/app/controllers/private/order_asks_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class OrderAsksController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderAsk.new(order_params(:order_ask))
      order_submit
    end

    def clear
      @orders = OrderAsk.where(member_id: current_user.id).with_state(:wait).with_market(current_market)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

    def currency
      "#{params[:ask]}#{params[:bid]}".to_sym
    end

  end
end

excoincial-peatio/app/helpers/private/history_helper.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private::HistoryHelper
  def trade_side(trade)
    trade.ask_member_id == current_user.id ? 'sell' : 'buy'
  end

  def transaction_type(t)
    t( ( t.currency.escrow? ? ".escrow" : "" ) +
       ".#{t.class.superclass.name}"
    ).split.map(&:capitalize).join(' ')
  end

  def display_currency(t)
    return t.currency.code.upcase unless t.currency.escrow?
    return ( "afcash" +
      display_escrow_agent( t.currency,' (#{agent} escrow)' ).to_s
    ).upcase
  end

  def display_escrow_agent(c,str="")
    return unless c.escrow? and str.present?
    begin
      agent = { vendescrow:"vendasity",
                foodescrow:"foodmoni"
      }.fetch(c.code.to_sym)
    rescue => e
      report_exception e
    end
    str = str.split(/\#\{[^\#\{\}]*\}/)
    return unless str.count > 1 and agent.present?
    return str.join(agent)
  end

  def transaction_txid_link(t)
    return t.txid if t.txid.blank? || !t.currency.coin?
    link_to t.txid, t.transaction_url
  end
end

excoincial-peatio/app/helpers/private/rewards_helper.rb
module Private::RewardsHelper
end

excoincial-peatio/app/views/private/withdraws/create.js.erb
// $(".flash-message").html('<div class="alert alert-dismissable alert-custom-success alert-success alert-msg" style="opacity: 0.239689;"><button class="close" type="button" data-dismiss="alert" aria-hidden="true"><i class="icon fa fa-times"></i></button><h3 class="h5 mb-0"><span>We sent a confirmation email to you. Please follow the instructions to confirm this withdrawal request.</span></h3></div>');
// $(".flash-message").fadeOut(10000);
$("#confirm_withdraw").modal({backdrop: 'static', keyboard: false});

excoincial-peatio/app/views/private/withdraws/show.html.erb
<div class="pagecontent">
  <div class="container-fluid site-container">
    <div class="bannerpage mt-20">
      <section class="">
        <div class="site-theme-form">
          <div class="row flex-content">
            <div class="col-md-4 col-sm-8 banner-border white-bgs signinbox center-content form-bg-banner pad-25 icon-form">
              <div class="split-box">
                <a href="/funds">Back</a>
                <div class="banner-border">
                  <h2 class="page-header text-uppercase text-center no-icon"> <%= @currency.id %> Withdraw
                    <hr class="x-line">
                  </h2>
                  <ul class="my-form-list">
                    <li>
                      Once you have submitted your withdrawal request, we will send you a confirmation email. Please click on the confirmation link sent to your email to authorize your withdrawal request.                      
                    </li>
                    <li>
                      Upon completing a withdrawal action you can track the progress on your <%= link_to "history",account_history_path %> page. 
                    </li>
                    <li>Minimum Withdrawal : <%= @currency.min_withdraw_amount %> <%= @currency.id.upcase %></li>
                  </ul>
                  <%= form_for @withdraw,  as: :withdraw,  url: withdraw_index_path, remote: true, class: "" do |f| %>
                    <div class="panel panel-content panel-default panel-border bottom-line">
                      <div class="panel-body pad-10">
                        <div class="text-center balance-level">Your Wallet Balance : <span class="g-t h4" id="click_balance"> <%= @account.balance.floor(@currency.precision) %> </span> <span> <%= @currency.id.upcase %> </span></div>
                        <div class="form-group">
                          <label class="col-xs-12 control-label">Receive Address</label>
                          <div class="col-xs-12 inputGroupContainer">
                            <%= f.text_field :rid, class: "form-control", required: true %>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-xs-12 control-label">Amount To Receive</label>
                          <div class="col-xs-12 inputGroupContainer">
                            <%= f.number_field :sum, step: :any, class: "form-control", required: true, min: 0.005, max: @account.balance.floor(@currency.precision) %>
                          </div>
                        </div>
                        <!-- <div class="text-right col-md-12"> Min withdraw amount : <span class="violet-t" id="netfee"> <%#= @currency.min_withdraw_amount %> </span> <span class="violet-t text-uppercase"> <%#= @currency.id %> </span> </div> -->
                        <div class="text-right col-md-12">Transaction Fee : <span class="violet-t" id="comm">  <%= @currency.withdraw_fee %> </span> <span class="violet-t text-uppercase"> <%= @currency.id %> </span></div>
<!--                        <div class="text-right col-md-12">Total Charge : <span class="violet-t" id="total"> 0 </span>  <span class="violet-t text-uppercase"> <%#= @currency.id %> </span> </div>-->
                        <div class="center-btn text-center form-group">
                          <%= f.submit :withdraw, class: "btn btn-gray site-btn mt-20 text-uppercase nova-font-bold" %>
                        </div>
                      </div>

                    </div>

                  <% end %>


                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<div class="modal custom-cnfrm-modal" id="confirm_withdraw" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="modal-icons">
          <p class="icon-i">
            <i class="fa fa-exclamation"></i>
          </p>
          <p class="modal-text">
            We sent a confirmation email to you. Please follow the instructions to confirm this withdrawal request.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#confirm_withdraw").hide();
  });
  $('form .balance-level').on('click', function () {
    $('#withdraw_sum').val($('#click_balance').html().trim())
  });
  $("#confirm_withdraw .close").on('click',function(){
    $("#confirm_withdraw").hide();
  });
</script>